### ISSUE TITLE
rename newClient to createClient for correct naming conventioning in nodejs world

### ISSUE THREAD

**Issue by googoid** [cozy/request-json#37]
title says everything

**Comment by frankrousseau** [comment]
Hi @googoid,

 Thank you for your suggestion. But I didn't know that. Do you have some reference? If that's the case, I would be glad to change it!

**Comment by googoid** [comment]
https://github.com/mranney/node_redis
redis.**createClient**

http://nodejs.org/api/http.html
http.**createServer**
http.**createClient**

:)

just leave old `newClient` for backward compatibility
yeah and use https://www.npmjs.com/package/depd to warn about deprecation in `newClient` method

**Comment by frankrousseau** [comment]
Ok, sounds nice. Could you open a PR and perform the modification?

**Comment by googoid** [comment]
https://github.com/cozy/request-json/pull/40

**Comment by frankrousseau** [comment]
Welcome to the Free and Open Source community! 

I published your change as a 0.5.1 version. About missed Pull Request, you don't need to close them an reopen them. When you commit something new it relaunches automatically the build on Travis.
