### ISSUE TITLE
[LIGHT] Incompatiblity node 0.12

### ISSUE THREAD

**Issue by aenario** [cozy/request-json#43]
https://github.com/cozy-labs/request-json-light/blob/master/main.coffee#L76-L79

These lines are weird : 
1 - the proper header is content-length
2 - if data is a JSON Object, .length is undefined. If its is an array, .length is not the content-length, if it is a string .length can be wrong with utf8...

They cause failure in node 0.12 (probably because of a header set but undefined)

**Comment by frankrousseau** [comment]
fixed
