### ISSUE TITLE
Query String Authentication

### ISSUE THREAD

**Issue by DanPantry** [cozy/request-json#45]
A lot of other libraries I've seen don't support this, and it gets rather.. frustrating. I understand you've just written a thin wrapper around `request` but it does not hurt to ask.

Some of the APIs I use utilize query string authentication, rather than `Authentication` HTTP headers or basic auth. For example, the [Riot API](https://developer.riotgames.com/api/) requires the appending of a query string key called `api_key` with your api key to the end of the URL. I really do like the syntax of `request.headers['foo'] = bar`. 

Is there any way a similar syntax could be introduced for query strings so that I don't have to manually construct the query string each time? It gets more painful when there are query string options for the API in addition to the api_key to construct it.

**Comment by DanPantry** [comment]
Never mind; `request` natively supports this with `request.verb(path, options, callback)` where options has an object with the key `qs`. apologies  - sometimes it helps to check the thin wrapper first.. :p

**Comment by frankrousseau** [comment]
You can add headers too to your requestJson client. Ex:

```
client = requestJson.createClient 'http://riot.com/api'
client.headers.foo = "bar"
```

**Comment by frankrousseau** [comment]
Whatever thank you for your interest in request-json!
