### ISSUE TITLE
delete request has no body

### ISSUE THREAD

**Issue by adithyaov** [cozy/request-json#61]
The delete request does not allow a request body! Is there another way I can send a delete request with a body?

**Comment by frankrousseau** [comment]
Hello,

I think you can call the handleMethod directly:

```coffeescript
 client.handleRequest('DELETE', path, body, options, callback, parse);
```

Does it work?

**Comment by adithyaov** [comment]
Getting back to this issue after 2 years feels weird. I apologize for leaving the contributors without any replies. I will close this issue as the method suggested seems to work. Again, I apologize for my long absence.

**Comment by frankrousseau** [comment]
No worry, we are all busy! Thank you for taking the time to close this issue.
